<a href="https://colab.research.google.com/github/moham882/FLYRANK_ML_INTENSHIP/blob/main/w02_ml_task_framing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML-03 — Frame Your Lane as an ML Task

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/moham882/flyrank_ml_internship/blob/main/work/notebooks/w02_ml_task_framing.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. My lane as an ML task (type)

*Classification, clustering, ranking, or scoring — which one, and why?*

In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/moham882/flyrank_ml_internship/main/data/raw/content_refresh_anonymized.csv"

df = pd.read_csv(url)

print(f"Rows: {len(df):,}")
print(f"Columns: {len(df.columns):,}")

df.head()

Rows: 30,000
Columns: 44

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

**Task type:** Ranking / scoring
I want to rank content items by priority so that an editor can decide which pages should be reviewed or improved first.
The model would produce a priority score for each content item. Higher-scoring items would be considered higher priority for review.

## 2. Target or proxy

*What would you predict? Where does that label come from — observed outcome or a defined rule?*

### Target or proxy

**Target / proxy:** `trend_pct`

I will use `trend_pct` as an observed performance signal for content priority. It measures the directional change in performance rather than being a label created from a hand-written rule.

For ranking, the goal is to give higher priority to content with weaker observed performance trends. This is a proxy for editorial review priority, not a claim that the model directly predicts future decline.

In [ ]:

print("Available columns:")
print(df.columns.tolist())
display(df.head())

Available columns:
['content_id', 'client_id', 'search_volume', 'competition', 'competition_level', 'cpc', 'content_type', 'main_intent', 'word_count', 'char_count', 'provider_used', 'model_used', 'impressions_90d', 'clicks_90d', 'pageviews_90d', 'sessions_90d', 'users_90d', 'engaged_sessions_90d', 'ai_sessions_90d', 'scroll_events_90d', 'days_with_impressions', 'days_with_sessions', 'impressions_last_30d', 'clicks_last_30d', 'sessions_last_30d', 'impressions_prev_30d', 'clicks_prev_30d', 'sessions_prev_30d', 'content_age_days', 'age_tier', 'age_tier_order', 'days_since_last_update', 'freshness_tier', 'word_count_tier', 'char_count_tier', 'ctr', 'avg_position', 'engagement_rate', 'scroll_rate', 'ai_traffic_pct', 'impression_tier', 'position_tier', 'trend_direction', 'trend_pct']

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

## 3. Success metric

*One metric you can defend. What number means 'good'?*

### Success metric

**Metric:** Precision@50

I will use Precision@50 to measure how useful the top 50 ranked content items are for the intended editorial action.

A higher Precision@50 means that a larger share of the highest-priority items correspond to the performance outcome I am trying to prioritize.

This metric matches the decision because an editor has limited time and needs a useful shortlist rather than a ranking that is equally accurate across every content item.

In [ ]:
ranking_column = "ctr"
target_column = "is_high_performer"

if ranking_column in df.columns and target_column in df.columns:
    top_50 = df.sort_values(ranking_column, ascending=False).head(50)
    precision_at_50 = top_50[target_column].mean()

    print(f"Precision@50: {precision_at_50:.3f}")
else:
    print("The example columns are not yet present.")
    print("Available columns:", df.columns.tolist())

The example columns are not yet present.
Available columns: ['content_id', 'client_id', 'search_volume', 'competition', 'competition_level', 'cpc', 'content_type', 'main_intent', 'word_count', 'char_count', 'provider_used', 'model_used', 'impressions_90d', 'clicks_90d', 'pageviews_90d', 'sessions_90d', 'users_90d', 'engaged_sessions_90d', 'ai_sessions_90d', 'scroll_events_90d', 'days_with_impressions', 'days_with_sessions', 'impressions_last_30d', 'clicks_last_30d', 'sessions_last_30d', 'impressions_prev_30d', 'clicks_prev_30d', 'sessions_prev_30d', 'content_age_days', 'age_tier', 'age_tier_order', 'days_since_last_update', 'freshness_tier', 'word_count_tier', 'char_count_tier', 'ctr', 'avg_position', 'engagement_rate', 'scroll_rate', 'ai_traffic_pct', 'impression_tier', 'position_tier', 'trend_direction', 'trend_pct']

## 4. The unit of analysis, as a real dataframe

*Load your lane's slice and show it: one row = one what?*

### The unit of analysis

**One row = one pseudonymized content item.**

The dataset contains content-level observations, so each row represents one content item and its associated performance metrics.

I will verify this by displaying actual rows and the dataframe dimensions below.

In [ ]:
print("Shape:", df.shape)
display(df.head())
print(f"Number of rows: {len(df):,}")
print(f"Number of columns: {len(df.columns):,}")

display(df.head(10))

Shape: (30000, 44)

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

Number of rows: 30,000
Number of columns: 44

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7
5,content_d4084a4bc775,client_f369cb89fc,720.0,1.00,HIGH,1.05,keyword article,transactional,3080.0,18178.0,...,15000-25000,0.03,8.5,0.00,25.00,0.0,good,page_1,down,-38.9
6,content_9a34b442b552,client_8722616204,0.0,0.00,LOW,0.00,keyword article,informational,3059.0,20810.0,...,15000-25000,0.00,7.0,0.00,0.00,0.0,low,page_1,down,-92.3
7,content_a63219c6e95a,client_19581e27de,590.0,0.44,MEDIUM,0.64,keyword article,commercial,NaN,NaN,...,NaN,0.06,21.2,3.57,7.14,0.0,moderate,page_3_5,stable,0.6
8,content_5e6c160719bc,client_6208ef0f77,0.0,0.00,LOW,0.00,keyword article,informational,3807.0,24228.0,...,15000-25000,0.09,46.0,5.88,6.25,0.0,excellent,page_3_5,down,-58.8
9,content_c27558df2b0c,client_19581e27de,0.0,0.00,LOW,0.00,keyword article,informational,NaN,NaN,...,NaN,0.16,4.9,0.00,0.00,0.0,moderate,page_1,down,-29.2

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 44 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   content_id              30000 non-null  object
 1   client_id               30000 non-null  object
 2   search_volume           27532 non-null  float64
 3   competition             27532 non-null  float64
 4   competition_level       27390 non-null  object
 5   cpc                     27532 non-null  float64
 6   content_type            30000 non-null  object
 7   main_intent             27626 non-null  object
 8   word_count              22301 non-null  float64
 9   char_count              22301 non-null  float64
 10  provider_used           8562 non-null   object
 11  model_used              24267 non-null  object
 12  impressions_90d         30000 non-null  int64
 13  clicks_90d              30000 non-null  int64
 14  pageviews_90d           30000 non-null  int64
 15  sessions_90d            30000 non-null  int64
 16  users_90d               30000 non-null  int64
 17  engaged_sessions_90d    30000 non-null  int64
 18  ai_sessions_90d         30000 non-null  int64
 19  scroll_events_90d       30000 non-null  int64
 20  days_with_impressions   30000 non-null  int64
 21  days_with_sessions      30000 non-null  int64
 22  impressions_last_30d    30000 non-null  int64
 23  clicks_last_30d         30000 non-null  int64
 24  sessions_last_30d       30000 non-null  int64
 25  impressions_prev_30d    30000 non-null  int64
 26  clicks_prev_30d         30000 non-null  int64
 27  sessions_prev_30d       30000 non-null  int64
 28  content_age_days        30000 non-null  int64
 29  age_tier                30000 non-null  object
 30  age_tier_order          30000 non-null  int64
 31  days_since_last_update  30000 non-null  int64
 32  freshness_tier          30000 non-null  object
 33  word_count_tier         22301 non-null  object
 34  char_count_tier         22301 non-null  object
 35  ctr                     30000 non-null  float64
 36  avg_position            30000 non-null  float64
 37  engagement_rate         30000 non-null  float64
 38  scroll_rate             29875 non-null  float64
 39  ai_traffic_pct          30000 non-null  float64
 40  impression_tier         30000 non-null  object
 41  position_tier           30000 non-null  object
 42  trend_direction         30000 non-null  object
 43  trend_pct               26612 non-null  float64
dtypes: float64(11), int64(19), object(14)
memory usage: 10.1+ MB

## 5. Why ML beats a fixed rule here

*What makes the pattern too messy for an if-statement?*

### Why ML beats a fixed rule

A fixed rule could prioritize content using one metric, such as saying that every item with a negative `trend_pct` should be reviewed first.

ML could be more useful if multiple signals interact in ways that are difficult to express with a simple hand-written rule. The model can combine several content and performance signals to produce a priority score.

However, ML only earns its place if it improves the decision-support outcome compared with a simple baseline rule. I would therefore compare the ML ranking against a fixed-rule baseline using Precision@50.

In [ ]:
numeric_cols = df.select_dtypes(include="number").columns.tolist()
print("Numeric features available for modelling/ranking:")
for col in numeric_cols:
    print("-", col)

Numeric features available for modelling/ranking:
- search_volume
- competition
- cpc
- word_count
- char_count
- impressions_90d
- clicks_90d
- pageviews_90d
- sessions_90d
- users_90d
- engaged_sessions_90d
- ai_sessions_90d
- scroll_events_90d
- days_with_impressions
- days_with_sessions
- impressions_last_30d
- clicks_last_30d
- sessions_last_30d
- impressions_prev_30d
- clicks_prev_30d
- sessions_prev_30d
- content_age_days
- age_tier_order
- days_since_last_update
- ctr
- avg_position
- engagement_rate
- scroll_rate
- ai_traffic_pct
- trend_pct

In [ ]:
display(df[numeric_cols].describe().T)

## Self-check

Before you submit, confirm each line honestly:

- ✅Every section above is filled — markdown thinking AND the code that backs it
- ✅The notebook runs top to bottom with no errors (Runtime → Run all)
- ✅No client names, URLs, or private queries anywhere
- ✅My claims use careful words: observed, measured, directional, decision-support
- ✅Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.